window.FENCE_CONFIG = {
	CARD_TYPES: [
		{
			key: 'jewel',
			singular: 'Jewel',
			plural: 'Jewels',
			count: 8,
			marketValue: 1200,
			price: 8500,
			accent: '#1a6f6d',
			imagePath: 'assets/cards/jewel.png'
		},
		{
			key: 'portrait',
			singular: 'Portrait',
			plural: 'Portraits',
			count: 7,
			marketValue: 1100,
			price: 6000,
			accent: '#8d6a22',
			imagePath: 'assets/cards/portrait.png'
		},
		{
			key: 'statue',
			singular: 'Statue',
			plural: 'Statues',
			count: 6,
			marketValue: 700,
			price: 3000,
			accent: '#8b5541',
			imagePath: 'assets/cards/statue.png'
		},
		{
			key: 'vase',
			singular: 'Vase',
			plural: 'Vases',
			count: 5,
			marketValue: 500,
			price: 2000,
			accent: '#617231',
			imagePath: 'assets/cards/vase.png'
		},
		{
			key: 'manuscript',
			singular: 'Manuscript',
			plural: 'Manuscripts',
			count: 4,
			marketValue: 450,
			price: 1200,
			accent: '#4d5967',
			imagePath: 'assets/cards/manuscript.png'
		},
		{
			key: 'clock',
			singular: 'Clock',
			plural: 'Clocks',
			count: 3,
			marketValue: 250,
			price: 500,
			accent: '#79563d',
			imagePath: 'assets/cards/clock.png'
		},
		{
			key: 'watch',
			singular: 'Watch',
			plural: 'Watches',
			count: 2,
			marketValue: 200,
			price: 130,
			accent: '#4d6e8f',
			imagePath: 'assets/cards/watch.png'
		},
		{
			key: 'silverware',
			singular: 'Silverware',
			plural: 'Silverware',
			count: 1,
			marketValue: 100,
			price: 30,
			accent: '#6e7478',
			imagePath: 'assets/cards/silverware.png'
		}
	],
	BUY_STAGE_SIZE: 12,
	TOTAL_BUY_STAGES: 3,
	MAX_HAND_SIZE: 6,
	STARTING_CREDIT: 10000,
	CREDIT_FLOOR: 8000,
	CREDIT_CEILING: 50000,
	SELL_ROUND_OVERHEAD: 300,
	SELL_ROUND_OVERHEAD_NOTICE_MS: 1450,
	HEAT_VALUES: [1, 2, 4, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 32, 36, 39, 42, 49, 53, 63, 76, 89, 93],
	TINTED_TYPE_IMAGE_KEYS: new Set(),
	THEME: {
		backgroundTop: '#101216',
		backgroundBottom: '#171b20',
		panel: '#1d2228',
		panelSoft: '#232930',
		panelMuted: '#2a3139',
		card: '#f7f1e3',
		cardBack: '#a8935f',
		cardText: '#2e2822',
		cardTextSoft: '#6f665a',
		text: '#f3eee4',
		textSoft: '#aab2bc',
		textMuted: '#7f8791',
		highlight: '#4ea89a',
		highlightSoft: '#34766c',
		highlightMuted: '#284e49',
		buttonBuy: '#34766c',
		buttonReject: '#6a463a',
		buttonSell: '#806226',
		buttonPrimary: '#34766c',
		buttonDisabled: '#3b434d',
		buttonTextDisabled: '#7f8791',
		heat: '#ff8a33',
		heatSoft: '#ffcb6b',
		heatFlash: '#ff5e2f'
	},
	MAIN_FONT: '"Atkinson Hyperlegible Mono", monospace',
	QUEUE_ANIMATION_MS: 760,
	HAND_ANIMATION_MS: 560,
	FLIP_PORTION: 0.28,
	OPENING_DEAL_STAGGER_MS: 260,
	CASH_TICKER_DURATION_MS: 1080,
	CASH_TICKER_MIN_SWING: 300,
	CASH_TICKER_CYCLES: 2.5,
	CARD_HEIGHT_RATIO: 1.3,
	HOW_TO_PLAY_INTRO:
		"Choose up to six items to buy. A high-value item raises the sell price of all matching items. For example, the most expensive <jewel icon>jewel card sells for $9,600. If you have that card, all your <jewel icon>jewel cards sell for $9,600.",
	HOW_TO_PLAY_HEAT_LINE: "The higher an item's",
	HOW_TO_PLAY_HEAT_OUTRO: 'the higher the chance it gets confiscated before you can sell it. You can hold items between rounds until the end of the week.',
	HOW_TO_PLAY_OUTRO: "You're dealt 12 cards per round, with 3 rounds in a week. These are the 36 cards in the deck:",
	SELL_HEAT_ROLL_MS: 2330,
	SELL_HEAT_LAND_MS: 1500,
	SELL_HEAT_FLASH_MS: 900,
	SELL_HEAT_RESULT_HOLD_MS: 550,
	SELL_HEAT_REEL_STAGGER_MS: 178,
	SELL_HEAT_REEL_OVERSHOOT_MS: 39,
	SELL_HEAT_REEL_SETTLE_MS: 31
}
